captcha:
  solver-service: "anti-captcha.com" # Or capmonster.cloud
  solver-key: ""

settings:
  invite_code: "https://discord.gg/5As5FZBYvA"
  threads: 5 
  rotating_proxy: "" # Format is username:password@host:port or host:port

token:MTEyNTIzODQyNTI3Mjk3OTU0Nw.GFh9DJ.RHiCeo53MFtdfO0nS2s0D_HKaRI3MK7IEc5D5c
  username: "" # Leave empty for random
